version: '3.8'

services:
  simplybook-mcp:
    build: .
    container_name: simplybook-mcp
    ports:
      - "8001:8001"  # SSE port only
    volumes:
      - ./src:/app/src
      - ./logs:/app/logs
    environment:
      - ENVIRONMENT=development
      - LOG_LEVEL=INFO
      - SIMPLYBOOK_COMPANY=${SIMPLYBOOK_COMPANY}
      - SIMPLYBOOK_LOGIN=${SIMPLYBOOK_LOGIN}
      - SIMPLYBOOK_PASSWORD=${SIMPLYBOOK_PASSWORD}
      - MCP_HOST=${MCP_HOST:-0.0.0.0}
      - MCP_PORT=${MCP_PORT:-8001}
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8001/sse"]
      interval: 60s
      timeout: 10s
      retries: 2
      start_period: 60s