version: '3.8'

services:
  simplybook-mcp:
    build: .
    container_name: simplybook-mcp
    ports:
      - "8001:8001"  # SSE port only
    volumes:
      - ./src:/app/src
      - ./logs:/app/logs
    environment:
      - ENVIRONMENT=development
      - LOG_LEVEL=INFO
      - SIMPLYBOOK_COMPANY=${SIMPLYBOOK_COMPANY}
      - SIMPLYBOOK_LOGIN=${SIMPLYBOOK_LOGIN}
      - SIMPLYBOOK_PASSWORD=${SIMPLYBOOK_PASSWORD}
      - ENABLE_API_LOGGING=${ENABLE_API_LOGGING:-true}
      - MCP_HOST=${MCP_HOST:-0.0.0.0}
      - MCP_PORT=${MCP_PORT:-8001}
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "bash", "/app/healthcheck.sh"]
      interval: 300s
      timeout: 30s
      retries: 3
      start_period: 120s